language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0

branches:
  only:
    - master
    - travis

sudo: false

addons:
  apt:
    packages:
      - lcov

before_install:
  - travis_retry gem install coveralls-lcov
  - travis_retry git submodule update --init --recursive
  - travis_retry git clone git://github.com/jbboehr/libmustache.git libmustache
  - cd libmustache
  - autoreconf -fiv
  - ./configure --prefix=$HOME/libmustache --without-mustache-spec
  - make
  - make install
  - cd ..

install:
  - phpize
  - ./configure --enable-mustache --with-libmustache=$HOME/libmustache CXXFLAGS="--coverage -fprofile-arcs -ftest-coverage" LDFLAGS="--coverage"
  - make clean all

script:
  - export NO_INTERACTION=1
  - export REPORT_EXIT_STATUS=1
  - export TEST_PHP_EXECUTABLE=`which php`
  - lcov --directory . --zerocounters
  - lcov --directory . --capture --initial --compat-libtool --output-file coverage.info
  - php run-tests.php -d extension=mustache.so -d extension_dir=modules -n ./tests/*.phpt
  - for i in `ls tests/*.out 2>/dev/null`; do echo "-- START ${i}"; cat $i; echo "-- END"; done
  - lcov --no-checksum --directory . --capture --compat-libtool --output-file coverage.info
  - lcov --remove coverage.info "/usr*" --remove coverage.info "*/libmustache/*" --remove coverage.info "*/.phpenv/*" --compat-libtool --output-file coverage.info

after_success:
  - coveralls-lcov coverage.info

