version: '{branch}.{build}'

branches:
  only:
  - master
  - appveyor
  - w32
  - windows

platform:
  - x86
  - x64

cache:
  - 'C:\Downloads -> appveyor.yml'

environment:
  PHP_SDK_BINARY_TOOLS_VER: 2.1.9
  NO_INTERACTION: 1
  REPORT_EXIT_STATUS: 1
  TEST_PHP_EXECUTABLE: C:\projects\php\php.exe

  matrix:
# note: json-c is currently failing to compile on < vc15
#    - PHP_VER: 7.0
#      VC_VER: vc14
#      PHP_BUILD_TYPE: Win32
#      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
#    - PHP_VER: 7.0
#      VC_VER: vc14
#      PHP_BUILD_TYPE: nts-Win32
#      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
#    - PHP_VER: 7.1
#      VC_VER: vc14
#      PHP_BUILD_TYPE: Win32
#      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
#    - PHP_VER: 7.1
#      VC_VER: vc14
#      PHP_BUILD_TYPE: nts-Win32
#      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
    - PHP_VER: 7.2
      VC_VER: vc15
      PHP_BUILD_TYPE: Win32
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    - PHP_VER: 7.2
      VC_VER: vc15
      PHP_BUILD_TYPE: nts-Win32
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015

install:
- cmd: cinst wget
- ps: Import-Module .\appveyor.psm1
- ps: InitializeBuildVars
- '"%VSCOMNTOOLS%\VsDevCmd" %PLATFORM%'
- '"%VSCOMNTOOLS%\..\..\VC\vcvarsall.bat" %ARCH%'
# json-c
- cmd: >-
    cd C:\projects
    
    git clone -b windows https://github.com/jbboehr/json-c.git
    
    cd json-c
    
    mkdir build
    
    cd build
    
    cmake -G "NMake Makefiles" -DCMAKE_INSTALL_PREFIX=\projects\output -DCMAKE_BUILD_TYPE=Release ..
    
    nmake
    
    nmake install
# libyaml
- cmd: >-
    cd C:\projects
    
    git clone https://github.com/yaml/libyaml
    
    cd libyaml
    
    mkdir build
    
    cd build
    
    cmake -G "NMake Makefiles" -DCMAKE_INSTALL_PREFIX=\projects\output -DCMAKE_BUILD_TYPE=Release ..
    
    nmake
    
    copy /Y *.lib \projects\output\lib\
    
    copy /Y ..\include\yaml.h \projects\output\include\
# getopt.h
- cmd: >-
    cd C:\projects
    
    git clone https://github.com/jbboehr/Getopt-for-Visual-Studio.git
    
    copy /Y Getopt-for-Visual-Studio\getopt.h output\include\
# dirent.h
- cmd: >-
    cd C:\projects
    
    git clone https://github.com/jbboehr/dirent.git
    
    copy /Y dirent\include\dirent.h output\include
# libmustache
- cmd: >-
    cd C:\projects\
    
    git clone https://github.com/jbboehr/libmustache.git
    
    cd C:\projects\libmustache
    
    git submodule update --init
    
    mkdir build
    
    cd build
    
    SET LIBYAML_PATH=\projects\output
    
    SET LIBJSON_PATH=\projects\output
    
    cmake -G "NMake Makefiles" -DCMAKE_INSTALL_PREFIX=\projects\output -DCMAKE_BUILD_TYPE=Release  ..
    
    nmake
    
    nmake install
- ps: SetupPhpVersionString
- ps: AppendSessionPath
- ps: EnsureRequiredDirectoriesPresent
- ps: Ensure7ZipIsInstalled
- ps: InstallSdk
- ps: InstallPhp
- ps: InstallPhpDevPack

build_script:
- cmd: cd %APPVEYOR_BUILD_FOLDER%
- phpsdk_setvars
- phpize
- ps: InitializeReleaseVars
- cmd: configure.bat --disable-all --enable-mustache --with-libmustache=C:\projects\output --with-prefix=C:\projects\php
- cmd: nmake 2> compile-errors.log 1> compile.log

test_script:
- cmd: nmake test

after_build:
- ps: PrepareReleasePackage

on_failure :
- ps: PrintLogs

artifacts:
  - path: '.\$(RELEASE_ZIPBALL).zip'
    name: master
    type: zip
